server:
    port: ${PORT:8862}
message: Configuracion de Customer en el servidor levantado!
spring: 
  datasource:
    driver-class-name: con.mysql.cj.jdbc.Driver
    password: 123456789
    url: jdbc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
    ussername: root
  jpa:
    hibernate:
    ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      uri: http://localhost:8860
